#!/bin/bash

# Partition device as follows:
# 64M boot partition, ext2
#   syslinux, boot partition, tce, tinycore and other small tools
# ??M rescue partition, iso9660
#   embedded isohybrid image, size depends on image to be embedded
# ??M data partition, vfat
#   all remaining space

set -e

label="$1"
dev="$2"

boot="${dev}1"

cat <<EOF
Temp dir: /tmp/$$
Label:    $label
Device:   $dev
Boot:     $boot
EOF

echo -n "Press enter..."

read
set -x

mkdir -p /tmp/$$

echo "Editing partition table"

echo \
  "o n p 1 - - t c a p w" \
  | sed -re 's/ +/\n/g; s/-//g;' \
  | fdisk "$dev" >/dev/null

echo "Writing master boot record"
dd if=/usr/share/syslinux/mbr.bin of="$dev"

echo "Creating filesystem"
# Format boot partition and copy files
mkfs.vfat -n "$label" "$boot"
mount "$boot" /tmp/$$
rsync -r boot /tmp/$$/
umount /tmp/$$
syslinux --install --directory /boot/syslinux "$boot"

echo "Done!"
rm -rf /tmp/$$
