#!/bin/bash

# Partition device as follows:
# 64M boot partition, ext2
#   syslinux, boot partition, tce, tinycore and other small tools
# ??M rescue partition, iso9660
#   embedded isohybrid image, size depends on image to be embedded
# ??M data partition, vfat
#   all remaining space

set -e

label="$1"
dev="$2"

boot="${dev}1"
data="${dev}2"

bootsize=$(du -s --apparent-size -BM boot | cut -f1 | egrep -o '[0-9]+')
bootsize=$((bootsize + 8))  # pad by 8MB just in case

cat <<EOF
Temp dir: /tmp/$$
Label:    $label
Device:   $dev
Boot:     $boot (${bootsize}M)
Data:     $data
EOF

echo -n "Press enter..."

read
set -x

mkdir -p /tmp/$$

echo "Editing partition table"

echo \
  "p o" \
  "n p 1 - +${bootsize}M" \
  "n p 2 - - t 2 c" \
  "a 1 p w" \
  | sed -re 's/ +/\n/g; s/-//g;' \
  | fdisk "$dev" >/dev/null

echo "Writing master boot record"
dd if=/usr/share/syslinux/mbr.bin of="$dev"

echo "Creating boot filesystem"
# Format boot partition and copy files
mkfs.ext2 -q -m 0 -L "$label.boot" "$boot"
mount "$boot" /tmp/$$
rsync -a boot/ /tmp/$$/
extlinux --install -s /tmp/$$/syslinux
umount /tmp/$$

echo "Creating data filesystem"
mkfs.vfat -n "$label" "$data"

echo "Done!"
rm -rf /tmp/$$
